# -*- coding: utf-8 -*-

# Author: Kimsong Sao
# Email: saokimsong@gmail.com
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssRules(object):
    def setupUi(self, AssRules):
        AssRules.setObjectName("AssRules")
        AssRules.resize(854, 591)
        self.groupBox_6 = QtWidgets.QGroupBox(AssRules)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 10, 881, 571))
        self.groupBox_6.setObjectName("groupBox_6")
        self.rulesTableWidget = QtWidgets.QTableWidget(self.groupBox_6)
        self.rulesTableWidget.setGeometry(QtCore.QRect(10, 160, 811, 391))
        self.rulesTableWidget.setObjectName("rulesTableWidget")
        self.rulesTableWidget.setColumnCount(5)
        self.rulesTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(4, item)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 30, 271, 111))
        self.groupBox_9.setObjectName("groupBox_9")
        self.btnFilterAnt = QtWidgets.QPushButton(self.groupBox_9)
        self.btnFilterAnt.setGeometry(QtCore.QRect(180, 50, 71, 23))
        self.btnFilterAnt.setObjectName("btnFilterAnt")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 20, 241, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.txtFilterContainAnt = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtFilterContainAnt.setObjectName("txtFilterContainAnt")
        self.horizontalLayout_5.addWidget(self.txtFilterContainAnt)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_10.setGeometry(QtCore.QRect(290, 30, 271, 111))
        self.groupBox_10.setObjectName("groupBox_10")
        self.btnFilterConseq = QtWidgets.QPushButton(self.groupBox_10)
        self.btnFilterConseq.setGeometry(QtCore.QRect(180, 50, 71, 23))
        self.btnFilterConseq.setObjectName("btnFilterConseq")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(11, 20, 241, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.txtFilterContainConsq = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.txtFilterContainConsq.setObjectName("txtFilterContainConsq")
        self.horizontalLayout_4.addWidget(self.txtFilterContainConsq)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(570, 30, 251, 111))
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget_3.setGeometry(QtCore.QRect(11, 22, 201, 74))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lblMinSupportFilter_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.lblMinSupportFilter_2.setObjectName("lblMinSupportFilter_2")
        self.verticalLayout_4.addWidget(self.lblMinSupportFilter_2)
        self.lblMinSupportFilter_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.lblMinSupportFilter_3.setObjectName("lblMinSupportFilter_3")
        self.verticalLayout_4.addWidget(self.lblMinSupportFilter_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblFomDateFilter = QtWidgets.QLabel(self.layoutWidget_3)
        self.lblFomDateFilter.setObjectName("lblFomDateFilter")
        self.verticalLayout_5.addWidget(self.lblFomDateFilter)
        self.lblToDateFilter = QtWidgets.QLabel(self.layoutWidget_3)
        self.lblToDateFilter.setObjectName("lblToDateFilter")
        self.verticalLayout_5.addWidget(self.lblToDateFilter)
        self.lblMinSupportFilter = QtWidgets.QLabel(self.layoutWidget_3)
        self.lblMinSupportFilter.setObjectName("lblMinSupportFilter")
        self.verticalLayout_5.addWidget(self.lblMinSupportFilter)
        self.lblMinConfFilter = QtWidgets.QLabel(self.layoutWidget_3)
        self.lblMinConfFilter.setObjectName("lblMinConfFilter")
        self.verticalLayout_5.addWidget(self.lblMinConfFilter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)

        self.retranslateUi(AssRules)
        QtCore.QMetaObject.connectSlotsByName(AssRules)

    def retranslateUi(self, AssRules):
        _translate = QtCore.QCoreApplication.translate
        AssRules.setWindowTitle(_translate("AssRules", "Association Rules"))
        self.groupBox_6.setTitle(_translate("AssRules", "Rules"))
        item = self.rulesTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AssRules", "Antecedent"))
        item = self.rulesTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AssRules", "Consequent"))
        item = self.rulesTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("AssRules", "Support (%)"))
        item = self.rulesTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("AssRules", "Confidence (%)"))
        self.groupBox_9.setTitle(_translate("AssRules", "Antecedent"))
        self.btnFilterAnt.setText(_translate("AssRules", "Filter"))
        self.label_11.setText(_translate("AssRules", "Contains"))
        self.groupBox_10.setTitle(_translate("AssRules", "Consequent"))
        self.btnFilterConseq.setText(_translate("AssRules", "Filter"))
        self.label_12.setText(_translate("AssRules", "Contains"))
        self.groupBox_8.setTitle(_translate("AssRules", "Information"))
        self.label_3.setText(_translate("AssRules", "From Date:"))
        self.label_4.setText(_translate("AssRules", "To Date:"))
        self.lblMinSupportFilter_2.setText(
            _translate("AssRules", "Min. Support (%):"))
        self.lblMinSupportFilter_3.setText(
            _translate("AssRules", "Min. Confidence (%):"))
        self.lblFomDateFilter.setText(_translate("AssRules", "12"))
        self.lblToDateFilter.setText(_translate("AssRules", "12"))
        self.lblMinSupportFilter.setText(_translate("AssRules", "12"))
        self.lblMinConfFilter.setText(_translate("AssRules", "12"))
