# -*- coding: utf-8 -*-

# Author: Kimsong Sao
# Email: saokimsong@gmail.com
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FreqItemset(object):
    def setupUi(self, FreqItemset):
        FreqItemset.setObjectName("FreqItemset")
        FreqItemset.resize(973, 625)
        self.groupBox_8 = QtWidgets.QGroupBox(FreqItemset)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 130, 241, 111))
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 22, 201, 74))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lblMinSupportFilter_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lblMinSupportFilter_2.setObjectName("lblMinSupportFilter_2")
        self.verticalLayout_4.addWidget(self.lblMinSupportFilter_2)
        self.lblMinSupportFilter_3 = QtWidgets.QLabel(self.layoutWidget)
        self.lblMinSupportFilter_3.setObjectName("lblMinSupportFilter_3")
        self.verticalLayout_4.addWidget(self.lblMinSupportFilter_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblFomDateFilter = QtWidgets.QLabel(self.layoutWidget)
        self.lblFomDateFilter.setObjectName("lblFomDateFilter")
        self.verticalLayout_5.addWidget(self.lblFomDateFilter)
        self.lblToDateFilter = QtWidgets.QLabel(self.layoutWidget)
        self.lblToDateFilter.setObjectName("lblToDateFilter")
        self.verticalLayout_5.addWidget(self.lblToDateFilter)
        self.lblMinSupportFilter = QtWidgets.QLabel(self.layoutWidget)
        self.lblMinSupportFilter.setObjectName("lblMinSupportFilter")
        self.verticalLayout_5.addWidget(self.lblMinSupportFilter)
        self.lblMinConfFilter = QtWidgets.QLabel(self.layoutWidget)
        self.lblMinConfFilter.setObjectName("lblMinConfFilter")
        self.verticalLayout_5.addWidget(self.lblMinConfFilter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.groupBox_5 = QtWidgets.QGroupBox(FreqItemset)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 241, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.btnFilterItemset = QtWidgets.QPushButton(self.groupBox_5)
        self.btnFilterItemset.setGeometry(QtCore.QRect(160, 80, 71, 23))
        self.btnFilterItemset.setObjectName("btnFilterItemset")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 221, 47))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.txtFilterContains = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.txtFilterContains.setObjectName("txtFilterContains")
        self.horizontalLayout_3.addWidget(self.txtFilterContains)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.chkShow = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.chkShow.setChecked(True)
        self.chkShow.setObjectName("chkShow")
        self.verticalLayout_3.addWidget(self.chkShow)
        self.itemsetTableWidget = QtWidgets.QTableWidget(FreqItemset)
        self.itemsetTableWidget.setGeometry(QtCore.QRect(260, 10, 691, 601))
        self.itemsetTableWidget.setObjectName("itemsetTableWidget")
        self.itemsetTableWidget.setColumnCount(4)
        self.itemsetTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.itemsetTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemsetTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemsetTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemsetTableWidget.setHorizontalHeaderItem(3, item)

        self.retranslateUi(FreqItemset)
        QtCore.QMetaObject.connectSlotsByName(FreqItemset)

    def retranslateUi(self, FreqItemset):
        _translate = QtCore.QCoreApplication.translate
        FreqItemset.setWindowTitle(_translate("FreqItemset", "Freq. Itemsets"))
        self.groupBox_8.setTitle(_translate("FreqItemset", "Information"))
        self.label_3.setText(_translate("FreqItemset", "From Date:"))
        self.label_4.setText(_translate("FreqItemset", "To Date:"))
        self.lblMinSupportFilter_2.setText(
            _translate("FreqItemset", "Min. Support (%):"))
        self.lblMinSupportFilter_3.setText(
            _translate("FreqItemset", "Min. Confidence (%):"))
        self.lblFomDateFilter.setText(_translate("FreqItemset", "12"))
        self.lblToDateFilter.setText(_translate("FreqItemset", "12"))
        self.lblMinSupportFilter.setText(_translate("FreqItemset", "12"))
        self.lblMinConfFilter.setText(_translate("FreqItemset", "12"))
        self.groupBox_5.setTitle(_translate("FreqItemset", "Filter Itemsets"))
        self.btnFilterItemset.setText(_translate("FreqItemset", "Filter"))
        self.label_6.setText(_translate("FreqItemset", "Contains:"))
        self.chkShow.setText(_translate(
            "FreqItemset", "Show Only Support >= Min. Support"))
        item = self.itemsetTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FreqItemset", "Itemsets"))
        item = self.itemsetTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FreqItemset", "Transactions"))
        item = self.itemsetTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FreqItemset", "Support Count"))
        item = self.itemsetTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FreqItemset", "Support (%)"))
