# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\MITE12\ksapriori\gui\item_list.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormItemList(object):
    def setupUi(self, FormItemList):
        FormItemList.setObjectName("FormItemList")
        FormItemList.resize(810, 524)
        self.itemListTableWidget = QtWidgets.QTableWidget(FormItemList)
        self.itemListTableWidget.setGeometry(QtCore.QRect(10, 160, 791, 351))
        self.itemListTableWidget.setObjectName("itemListTableWidget")
        self.itemListTableWidget.setColumnCount(6)
        self.itemListTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.itemListTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemListTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemListTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemListTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemListTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemListTableWidget.setHorizontalHeaderItem(5, item)
        self.groupBox = QtWidgets.QGroupBox(FormItemList)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 791, 141))
        self.groupBox.setObjectName("groupBox")
        self.btnApplyFilter = QtWidgets.QPushButton(self.groupBox)
        self.btnApplyFilter.setGeometry(QtCore.QRect(384, 110, 81, 23))
        self.btnApplyFilter.setObjectName("btnApplyFilter")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 691, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txtCode = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtCode.setObjectName("txtCode")
        self.verticalLayout.addWidget(self.txtCode)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.txtLabel = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtLabel.setObjectName("txtLabel")
        self.verticalLayout_2.addWidget(self.txtLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.txtDescription = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtDescription.setObjectName("txtDescription")
        self.verticalLayout_3.addWidget(self.txtDescription)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.txtDescription2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtDescription2.setObjectName("txtDescription2")
        self.verticalLayout_4.addWidget(self.txtDescription2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 90, 341, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.txtUnitMeasure = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txtUnitMeasure.setObjectName("txtUnitMeasure")
        self.verticalLayout_5.addWidget(self.txtUnitMeasure)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.txtUnitPrice = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txtUnitPrice.setObjectName("txtUnitPrice")
        self.verticalLayout_6.addWidget(self.txtUnitPrice)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)

        self.retranslateUi(FormItemList)
        QtCore.QMetaObject.connectSlotsByName(FormItemList)

    def retranslateUi(self, FormItemList):
        _translate = QtCore.QCoreApplication.translate
        FormItemList.setWindowTitle(_translate("FormItemList", "Item List"))
        item = self.itemListTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormItemList", "Code"))
        item = self.itemListTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormItemList", "Label"))
        item = self.itemListTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormItemList", "Description"))
        item = self.itemListTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FormItemList", "Description 2"))
        item = self.itemListTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FormItemList", "Base Unit of Measure"))
        item = self.itemListTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FormItemList", "Unit Price"))
        self.groupBox.setTitle(_translate("FormItemList", "Filter"))
        self.btnApplyFilter.setText(_translate("FormItemList", "Apply Filter"))
        self.label_2.setText(_translate("FormItemList", "Code"))
        self.label_3.setText(_translate("FormItemList", "Label"))
        self.label_4.setText(_translate("FormItemList", "Description"))
        self.label_5.setText(_translate("FormItemList", "Description 2"))
        self.label_6.setText(_translate("FormItemList", "Unit of Measure"))
        self.label_7.setText(_translate("FormItemList", "Unit Price"))
