# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\MyMasterThesis\ksapriori\gui\main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(469, 239)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 210, 491, 321))
        self.groupBox_3.setObjectName("groupBox_3")
        self.itemsetTableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.itemsetTableWidget.setGeometry(QtCore.QRect(10, 330, 471, 311))
        self.itemsetTableWidget.setObjectName("itemsetTableWidget")
        self.itemsetTableWidget.setColumnCount(4)
        self.itemsetTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.itemsetTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemsetTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemsetTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemsetTableWidget.setHorizontalHeaderItem(3, item)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 200, 241, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.btnFilterItemset = QtWidgets.QPushButton(self.groupBox_5)
        self.btnFilterItemset.setGeometry(QtCore.QRect(160, 80, 71, 23))
        self.btnFilterItemset.setObjectName("btnFilterItemset")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 221, 47))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.txtFilterContains = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtFilterContains.setObjectName("txtFilterContains")
        self.horizontalLayout_3.addWidget(self.txtFilterContains)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.chkShow = QtWidgets.QCheckBox(self.layoutWidget)
        self.chkShow.setChecked(True)
        self.chkShow.setObjectName("chkShow")
        self.verticalLayout_3.addWidget(self.chkShow)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_8.setGeometry(QtCore.QRect(260, 200, 221, 111))
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 22, 201, 74))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lblMinSupportFilter_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.lblMinSupportFilter_2.setObjectName("lblMinSupportFilter_2")
        self.verticalLayout_4.addWidget(self.lblMinSupportFilter_2)
        self.lblMinSupportFilter_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.lblMinSupportFilter_3.setObjectName("lblMinSupportFilter_3")
        self.verticalLayout_4.addWidget(self.lblMinSupportFilter_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblFomDateFilter = QtWidgets.QLabel(self.layoutWidget1)
        self.lblFomDateFilter.setObjectName("lblFomDateFilter")
        self.verticalLayout_5.addWidget(self.lblFomDateFilter)
        self.lblToDateFilter = QtWidgets.QLabel(self.layoutWidget1)
        self.lblToDateFilter.setObjectName("lblToDateFilter")
        self.verticalLayout_5.addWidget(self.lblToDateFilter)
        self.lblMinSupportFilter = QtWidgets.QLabel(self.layoutWidget1)
        self.lblMinSupportFilter.setObjectName("lblMinSupportFilter")
        self.verticalLayout_5.addWidget(self.lblMinSupportFilter)
        self.lblMinConfFilter = QtWidgets.QLabel(self.layoutWidget1)
        self.lblMinConfFilter.setObjectName("lblMinConfFilter")
        self.verticalLayout_5.addWidget(self.lblMinConfFilter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(520, 10, 601, 651))
        self.groupBox_6.setObjectName("groupBox_6")
        self.rulesTableWidget = QtWidgets.QTableWidget(self.groupBox_6)
        self.rulesTableWidget.setGeometry(QtCore.QRect(10, 120, 551, 521))
        self.rulesTableWidget.setObjectName("rulesTableWidget")
        self.rulesTableWidget.setColumnCount(5)
        self.rulesTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTableWidget.setHorizontalHeaderItem(4, item)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 30, 271, 81))
        self.groupBox_9.setObjectName("groupBox_9")
        self.btnFilterAnt = QtWidgets.QPushButton(self.groupBox_9)
        self.btnFilterAnt.setGeometry(QtCore.QRect(180, 50, 71, 23))
        self.btnFilterAnt.setObjectName("btnFilterAnt")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 20, 241, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.txtFilterContainAnt = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txtFilterContainAnt.setObjectName("txtFilterContainAnt")
        self.horizontalLayout_5.addWidget(self.txtFilterContainAnt)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_10.setGeometry(QtCore.QRect(290, 30, 271, 81))
        self.groupBox_10.setObjectName("groupBox_10")
        self.btnFilterConseq = QtWidgets.QPushButton(self.groupBox_10)
        self.btnFilterConseq.setGeometry(QtCore.QRect(180, 50, 71, 23))
        self.btnFilterConseq.setObjectName("btnFilterConseq")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 20, 241, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.txtFilterContainConsq = QtWidgets.QLineEdit(self.layoutWidget3)
        self.txtFilterContainConsq.setObjectName("txtFilterContainConsq")
        self.horizontalLayout_4.addWidget(self.txtFilterContainConsq)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 481, 201))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btnRunApriori = QtWidgets.QPushButton(self.groupBox_4)
        self.btnRunApriori.setGeometry(QtCore.QRect(210, 140, 151, 23))
        self.btnRunApriori.setObjectName("btnRunApriori")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(13, 32, 351, 102))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lblMinSupport = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblMinSupport.setObjectName("lblMinSupport")
        self.verticalLayout_2.addWidget(self.lblMinSupport)
        self.lblMaxNumItemsets = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblMaxNumItemsets.setObjectName("lblMaxNumItemsets")
        self.verticalLayout_2.addWidget(self.lblMaxNumItemsets)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtFromDate = QtWidgets.QDateEdit(self.layoutWidget_2)
        self.txtFromDate.setCalendarPopup(True)
        self.txtFromDate.setObjectName("txtFromDate")
        self.verticalLayout.addWidget(self.txtFromDate)
        self.txtToDate = QtWidgets.QDateEdit(self.layoutWidget_2)
        self.txtToDate.setCalendarPopup(True)
        self.txtToDate.setObjectName("txtToDate")
        self.verticalLayout.addWidget(self.txtToDate)
        self.minSupportSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.minSupportSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.minSupportSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minSupportSpinBox.setDecimals(4)
        self.minSupportSpinBox.setMinimum(0.0001)
        self.minSupportSpinBox.setMaximum(100.0)
        self.minSupportSpinBox.setSingleStep(0.0001)
        self.minSupportSpinBox.setObjectName("minSupportSpinBox")
        self.verticalLayout.addWidget(self.minSupportSpinBox)
        self.minConfSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.minConfSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.minConfSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minConfSpinBox.setDecimals(0)
        self.minConfSpinBox.setMinimum(1.0)
        self.minConfSpinBox.setMaximum(100.0)
        self.minConfSpinBox.setSingleStep(1.0)
        self.minConfSpinBox.setProperty("value", 10.0)
        self.minConfSpinBox.setObjectName("minConfSpinBox")
        self.verticalLayout.addWidget(self.minConfSpinBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 469, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        self.menuImport_Data = QtWidgets.QMenu(self.menubar)
        self.menuImport_Data.setObjectName("menuImport_Data")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionImport_Items = QtWidgets.QAction(MainWindow)
        self.actionImport_Items.setVisible(False)
        self.actionImport_Items.setObjectName("actionImport_Items")
        self.actionImport_Transaction_Sales = QtWidgets.QAction(MainWindow)
        self.actionImport_Transaction_Sales.setObjectName("actionImport_Transaction_Sales")
        self.actionItem_List = QtWidgets.QAction(MainWindow)
        self.actionItem_List.setVisible(False)
        self.actionItem_List.setObjectName("actionItem_List")
        self.actionSales_Transaction = QtWidgets.QAction(MainWindow)
        self.actionSales_Transaction.setObjectName("actionSales_Transaction")
        self.actionActivity_Log = QtWidgets.QAction(MainWindow)
        self.actionActivity_Log.setObjectName("actionActivity_Log")
        self.actionReports = QtWidgets.QAction(MainWindow)
        self.actionReports.setObjectName("actionReports")
        self.actionAssociation_Rules = QtWidgets.QAction(MainWindow)
        self.actionAssociation_Rules.setObjectName("actionAssociation_Rules")
        self.actionFreq_Itemset = QtWidgets.QAction(MainWindow)
        self.actionFreq_Itemset.setObjectName("actionFreq_Itemset")
        self.actionAssociation_Rules_2 = QtWidgets.QAction(MainWindow)
        self.actionAssociation_Rules_2.setObjectName("actionAssociation_Rules_2")
        self.actionreport = QtWidgets.QAction(MainWindow)
        self.actionreport.setObjectName("actionreport")
        self.actionImport_Data = QtWidgets.QAction(MainWindow)
        self.actionImport_Data.setObjectName("actionImport_Data")
        self.menu_File.addAction(self.action_Exit)
        self.menuImport_Data.addAction(self.actionFreq_Itemset)
        self.menuImport_Data.addAction(self.actionAssociation_Rules_2)
        self.menuImport_Data.addSeparator()
        self.menuImport_Data.addAction(self.actionreport)
        self.menuTool.addAction(self.actionImport_Data)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuImport_Data.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Recommendation Sys. using Association Item Analysis"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Frequent Itemsets"))
        item = self.itemsetTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Itemsets"))
        item = self.itemsetTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Transactions"))
        item = self.itemsetTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Support Count"))
        item = self.itemsetTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Support (%)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Filter Itemsets"))
        self.btnFilterItemset.setText(_translate("MainWindow", "Filter"))
        self.label_6.setText(_translate("MainWindow", "Contains:"))
        self.chkShow.setText(_translate("MainWindow", "Show Only Support >= Min. Support"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Information"))
        self.label_3.setText(_translate("MainWindow", "From Date:"))
        self.label_4.setText(_translate("MainWindow", "To Date:"))
        self.lblMinSupportFilter_2.setText(_translate("MainWindow", "Min. Support (%):"))
        self.lblMinSupportFilter_3.setText(_translate("MainWindow", "Min. Confidence (%):"))
        self.lblFomDateFilter.setText(_translate("MainWindow", "12"))
        self.lblToDateFilter.setText(_translate("MainWindow", "12"))
        self.lblMinSupportFilter.setText(_translate("MainWindow", "12"))
        self.lblMinConfFilter.setText(_translate("MainWindow", "12"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Rules"))
        item = self.rulesTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Antecedent"))
        item = self.rulesTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Consequent"))
        item = self.rulesTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Support (%)"))
        item = self.rulesTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Confidence (%)"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Antecedent"))
        self.btnFilterAnt.setText(_translate("MainWindow", "Filter"))
        self.label_11.setText(_translate("MainWindow", "Contains"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Consequent"))
        self.btnFilterConseq.setText(_translate("MainWindow", "Filter"))
        self.label_12.setText(_translate("MainWindow", "Contains"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Find Itemsets && Rules"))
        self.btnRunApriori.setText(_translate("MainWindow", "Run Apriori"))
        self.label.setText(_translate("MainWindow", "From Invoice Date:"))
        self.label_2.setText(_translate("MainWindow", "To Invoice Date:"))
        self.lblMinSupport.setText(_translate("MainWindow", "Min. Support(%):"))
        self.lblMaxNumItemsets.setText(_translate("MainWindow", "Min. Confidence (%):"))
        self.txtFromDate.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy"))
        self.txtToDate.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_About.setTitle(_translate("MainWindow", "&About"))
        self.menuImport_Data.setTitle(_translate("MainWindow", "View"))
        self.menuTool.setTitle(_translate("MainWindow", "Tool"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_New.setText(_translate("MainWindow", "&New"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.actionImport_Items.setText(_translate("MainWindow", "Import Data"))
        self.actionImport_Transaction_Sales.setText(_translate("MainWindow", "Import Transaction Sales"))
        self.actionItem_List.setText(_translate("MainWindow", "Item List"))
        self.actionSales_Transaction.setText(_translate("MainWindow", "Sales Transaction"))
        self.actionActivity_Log.setText(_translate("MainWindow", "Freq. Itemset"))
        self.actionReports.setText(_translate("MainWindow", "Reports"))
        self.actionAssociation_Rules.setText(_translate("MainWindow", "Association Rules"))
        self.actionFreq_Itemset.setText(_translate("MainWindow", "Freq. Itemset"))
        self.actionAssociation_Rules_2.setText(_translate("MainWindow", "Association Rules"))
        self.actionreport.setText(_translate("MainWindow", "Performance"))
        self.actionImport_Data.setText(_translate("MainWindow", "Import Data"))
