# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\MITE12\ksapriori\gui\sales_transaction.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormSalesTransaction(object):
    def setupUi(self, FormSalesTransaction):
        FormSalesTransaction.setObjectName("FormSalesTransaction")
        FormSalesTransaction.resize(989, 466)
        self.groupBox = QtWidgets.QGroupBox(FormSalesTransaction)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 181, 451))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(80, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 31, 151, 140))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.fromDate = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.fromDate.setFont(font)
        self.fromDate.setObjectName("fromDate")
        self.verticalLayout.addWidget(self.fromDate)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.toDate = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.toDate.setFont(font)
        self.toDate.setObjectName("toDate")
        self.verticalLayout.addWidget(self.toDate)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.tableWidget = QtWidgets.QTableWidget(FormSalesTransaction)
        self.tableWidget.setGeometry(QtCore.QRect(200, 20, 781, 441))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)

        self.retranslateUi(FormSalesTransaction)
        QtCore.QMetaObject.connectSlotsByName(FormSalesTransaction)

    def retranslateUi(self, FormSalesTransaction):
        _translate = QtCore.QCoreApplication.translate
        FormSalesTransaction.setWindowTitle(_translate("FormSalesTransaction", "Sales Transaction"))
        self.groupBox.setTitle(_translate("FormSalesTransaction", "Filters"))
        self.pushButton.setText(_translate("FormSalesTransaction", "Search"))
        self.label.setText(_translate("FormSalesTransaction", "From Date"))
        self.label_2.setText(_translate("FormSalesTransaction", "To Date"))
        self.label_3.setText(_translate("FormSalesTransaction", "Item Code"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormSalesTransaction", "Document No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormSalesTransaction", "Posting Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormSalesTransaction", "Item Code"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FormSalesTransaction", "Item Label"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FormSalesTransaction", "Description"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FormSalesTransaction", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("FormSalesTransaction", "Price"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("FormSalesTransaction", "Amount"))
